{{- if .Values.random.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.random.jobname }} 
spec:
  template:
    spec:
      volumes:
      - name: "fio-config-{{ .Values.random.jobname }}"
        configMap:
          name: {{ .Values.random.jobname }} 
      - name: data-volume
        persistentVolumeClaim:
          claimName: "fio-pvc"
      containers:
      - name: fio
        image: artifacts.endress.com/docker-mirror/xridge/fio
        args:
        - --output-format=json
        - --output=/datadir/fio-random.json
        - /opt/fio/fio-random.job
        command: ["fio", "/opt/fio/fio-random.job"]
        volumeMounts:
        - name: "fio-config-{{ .Values.random.jobname }}"
          mountPath: /opt/fio
        - name: data-volume
          mountPath: /datadir
      - name: busybox
        image: artifacts.endress.com/docker-mirror/busybox
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: data-volume
          mountPath: /datadir
      restartPolicy: OnFailure
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - ideweiiss8508
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "fio-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: 10Gi
{{- if .Values.sequential.enabled }}        
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.sequential.jobname }}
spec:
  template:
    spec:
      volumes:
      - name: "fio-config-{{ .Values.sequential.jobname }}"
        configMap:
          name: "{{ .Values.sequential.jobname }}"
      - name: data-volume
        persistentVolumeClaim:
          claimName: fio-pvc
      containers:
      - name: fio
        image: artifacts.endress.com/docker-mirror/xridge/fio
        args:
        - --output-format=json
        - --output=/datadir/fio-sequential.json
        - /opt/fio/fio-sequential.job
        command: ["fio", "/opt/fio/fio-sequential.job"]
        volumeMounts:
        - name: "fio-config-{{ .Values.sequential.jobname }}"
          mountPath: /opt/fio
        - name: data-volume
          mountPath: /datadir
      - name: busybox
        image: artifacts.endress.com/docker-mirror/busybox
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: data-volume
          mountPath: /datadir
      restartPolicy: OnFailure
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ideweiiss8508
{{- end }}
